# Generated by Django 4.2.1 on 2023-09-20 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='City',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.IntegerField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
